#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"

    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # Disable statusline separator, if you want to use other value, please
    statusline_separator = "curve"
    statusline_iseparator = "arrow"
    buffer_index_type = 0
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    guifont = "BitstreamVeraSansMono Nerd Font:h9"

    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    enable_filetree_gitstatus = true

[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_smooth_scrolling = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'

[[layers]]
name = 'lang#python'
enabled_linters = ['flake8']

[[layers]]
name = 'gtags'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'denite'

[[layers]]
name = 'git'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'lsp'

[[custom_plugins]]
repo = 'tmhedberg/SimpylFold'
merged = false

[[custom_plugins]]
repo = 'Coacher/vim-virtualenv'
merged = false

[[custom_plugins]]
repo = 'vim-scripts/Tail-Bundle'
merged = false

[[custom_plugins]]
repo = 'https://gitlab.com/LazyLeopard/vimya'
depends = 'vim-scripts/Tail-Bundle'
merged = false

[[custom_plugins]]
repo = 'Coacher/vim-virtualenv'
merged = false

[[custom_plugins]]
repo = 'bkad/CamelCaseMotion'
merged = false

[[custom_plugins]]
repo = 'xolox/vim-misc'
merged = false

[[custom_plugins]]
repo = 'xolox/vim-session'
merged = false

